version: '3.8'

services:
  dsdc_app:
    image: brazeiro63/dsdc:latest
    # container_name: dsdc_app
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=3c65f2d9dad74920cf363e96ba6ace45
      - DATABASE_URL=postgresql://dsdc_user:3c65f2d9dad74920cf363e96ba6ace45@postgres:5432/dsdc_database
    ports:
      - "5000:8000"
    networks:
      - DSDCNet
    command: ["gunicorn", "-w", "4", "run:app", "-b", "0.0.0.0:8000"]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        
  web:
    image: nginx:alpine
    volumes:
      - /home/brazeiro63/dsdc/nginx/default.conf:/etc/nginx/conf.d/dsdc.conf
      - /home/brazeiro63/dsdc/app/static:/usr/share/nginx/html/static
    networks:
      - DSDCNet
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # Router HTTP: redireciona para HTTPS
        - "traefik.http.routers.dsdc-http.rule=Host(`dsdctecnologia.com.br`) || Host(`www.dsdctecnologia.com.br`)"
        - "traefik.http.routers.dsdc-http.entrypoints=web"
        - "traefik.http.routers.dsdc-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # Router HTTPS: serve o site com TLS
        - "traefik.http.routers.dsdc.rule=Host(`dsdctecnologia.com.br`) || Host(`www.dsdctecnologia.com.br`)"
        - "traefik.http.routers.dsdc.entrypoints=websecure"
        - "traefik.http.routers.dsdc.tls.certresolver=letsencryptresolver"
        # Diga explicitamente ao Traefik qual porta usar:
        - "traefik.http.services.dsdc.loadbalancer.server.port=80"

networks:
  DSDCNet:
    external: true