version: '3.8'
services:
  dsdc-site:
    build: .
    container_name: dsdc-site
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app
